<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXEaUBjr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXEaUBjr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXEaUBjr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXEaUBjr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXEaUBjr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XEaUBjr',
    'container.build_id' => '15565f43',
    'container.build_time' => 1573730797,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXEaUBjr');
