<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HEH17SB' shared service.

return $this->privates['.service_locator.HEH17SB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ticket' => ['privates', '.errored..service_locator.HEH17SB.App\\Entity\\Ticket', NULL, 'Cannot autowire service ".service_locator.HEH17SB": it references class "App\\Entity\\Ticket" but no such service exists.'],
], [
    'ticket' => 'App\\Entity\\Ticket',
]);
